#####################################################################
# Configuration Spring de base
#####################################################################
spring:
  application:
    name:                   eureka-discovery-server

server:
  port:                     8300


#désactivation auto-découverte
eureka:
  client:
    register-with-eureka:   false

    fetch-registry:         false

logging:
  level:
    com.netflix.eureka:     OFF
    com.netflix.discovery:  OFF

#####################################################################
# Configuration Spring actuator
#####################################################################
management:
  security:
    enabled:                         false
  context-path:                      /actuator
# configuration des endpoints
endpoints:
  hypermedia:
    enabled:                         true
  actuator:
    enabled:                         true
  beans:
    enabled:                         true
  env:
    enabled:                         true
  metrics:
    enabled:                         true
  health:
    enabled:                         true
  mappings:
    enabled:                         true
  docs:
    enabled:                         true
  logfile:
    enabled:                         true